// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhztnomgjzvzmapdflgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoenRub21nanp2em1hcGRmbGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTgyNjQsImV4cCI6MjA2MjgzNDI2NH0.Q2lwr9xG2RXBMdx-Q8bHMtm7QW63q3vBhzakFM3mFCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);